server:
  port: 8081
spring:
  application.name: reservation-service
  datasource:
    url: jdbc:postgresql://localhost:5432/reservation_db
    username: postgres
    password: root
  jpa:
    hibernate.ddl-auto: update
    open-in-view: false

management:
  health:
    rabbit:
      enabled: false
