server:
  port: 8082
spring:
  application.name: stall-service
  datasource:
    url: jdbc:postgresql://localhost:5432/stall_db
    username: postgres
    password: root
  jpa:
    hibernate.ddl-auto: update
    open-in-view: false
